# Generated by Django 2.1.7 on 2019-11-10 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FukushuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ABC〇〇〇', max_length=50)),
                ('problem1', models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default='secondary', max_length=50)),
                ('date1', models.DateField(default=datetime.datetime(2019, 11, 10, 15, 3, 0, 785868, tzinfo=utc))),
                ('problem2', models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default='secondary', max_length=50)),
                ('date2', models.DateField(default=datetime.datetime(2019, 11, 10, 15, 3, 0, 785868, tzinfo=utc))),
                ('problem3', models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default='secondary', max_length=50)),
                ('date3', models.DateField(default=datetime.datetime(2019, 11, 10, 15, 3, 0, 785868, tzinfo=utc))),
                ('problem4', models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default='secondary', max_length=50)),
                ('date4', models.DateField(default=datetime.datetime(2019, 11, 10, 15, 3, 0, 785868, tzinfo=utc))),
            ],
        ),
    ]
