# Generated by Django 2.1.7 on 2019-11-17 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fukushumodel',
            name='date1',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 13, 39, 34, 919695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fukushumodel',
            name='date2',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 13, 39, 34, 919695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fukushumodel',
            name='date3',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 13, 39, 34, 919695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fukushumodel',
            name='date4',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 13, 39, 34, 919695, tzinfo=utc)),
        ),
    ]
