# Generated by Django 2.1.7 on 2019-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shohinmei', models.CharField(max_length=100)),
                ('tenmei', models.CharField(max_length=50)),
                ('kakaku', models.IntegerField(default=0)),

            ],
        ),
    ]
