# Generated by Django 2.1.7 on 2019-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shohin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
