# Generated by Django 2.1.7 on 2019-10-20 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shohin', '0003_auto_20191012_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shohin',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 15, 10, 30, 973937, tzinfo=utc)),
        ),
    ]
