# Generated by Django 2.1.7 on 2019-10-22 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shohin', '0004_auto_20191021_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shohin',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 12, 54, 16, 410306, tzinfo=utc)),
        ),
    ]
