# Generated by Django 2.1.7 on 2019-10-22 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shohin', '0005_auto_20191022_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shohin',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 14, 31, 26, 750740, tzinfo=utc)),
        ),
    ]
