# Generated by Django 2.1.7 on 2019-11-17 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shohin', '0007_auto_20191117_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shohin',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 14, 32, 52, 688840, tzinfo=utc)),
        ),
    ]
