# Generated by Django 2.1.7 on 2019-11-17 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Kounyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='購入日')),
                ('tanka', models.IntegerField(help_text='税抜価格', verbose_name='金額')),
                ('kazu', models.IntegerField(verbose_name='数')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kounyu.Category', verbose_name='ｶﾃｺﾞﾘ')),
            ],
            options={
                'db_table': 'kounyu',
            },
        ),
        migrations.CreateModel(
            name='Shosha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'shosya',
            },
        ),
        migrations.AddField(
            model_name='kounyu',
            name='shosha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kounyu.Shosha', verbose_name='商社'),
        ),
    ]
