# Generated by Django 2.1.7 on 2019-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kounyu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ｶﾃｺﾞﾘ', 'verbose_name_plural': 'ｶﾃｺﾞﾘ'},
        ),
        migrations.AlterModelOptions(
            name='kounyu',
            options={'verbose_name': '購入', 'verbose_name_plural': '購入'},
        ),
        migrations.AlterModelOptions(
            name='shosha',
            options={'verbose_name': '商社', 'verbose_name_plural': '商社'},
        ),
        migrations.AlterField(
            model_name='kounyu',
            name='memo',
            field=models.CharField(blank=True, max_length=255, verbose_name='備考'),
        ),
    ]
