# Generated by Django 2.1.7 on 2019-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kounyu', '0002_auto_20191117_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kounyu',
            name='memo',
            field=models.CharField(blank=True, help_text='ｶﾀｶﾅ、ｱﾙﾌｧﾍﾞｯﾄは半角で', max_length=255, verbose_name='備考'),
        ),
    ]
