# Generated by Django 2.1.7 on 2019-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kounyu', '0003_auto_20191117_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shozoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '所属',
                'verbose_name_plural': '所属',
                'db_table': 'shozoku',
            },
        ),
    ]
