# Generated by Django 2.1.7 on 2019-11-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kounyu', '0004_shozoku'),
    ]

    operations = [
        migrations.AddField(
            model_name='kounyu',
            name='shozoku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kounyu.Shozoku', verbose_name='所属'),
            preserve_default=False,
        ),
    ]
